/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package melhorespassagens.telas;

/**
 *
 * @author crisd
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Splash
     */
    public Menu() {
        initComponents();
         

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaInicial = new javax.swing.JPanel();
        areaMenu = new javax.swing.JPanel();
        logoBranca = new javax.swing.JLabel();
        botoesMenu = new javax.swing.JPanel();
        botaoVoos = new javax.swing.JButton();
        botaoPassageiros = new javax.swing.JButton();
        botaoReservas = new javax.swing.JButton();
        botaoCancelamentos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Melhores Passagens | Menu");
        setBackground(new java.awt.Color(255, 102, 0));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/favicon.png")).getImage());
        setResizable(false);

        telaInicial.setBackground(new java.awt.Color(255, 255, 255));
        telaInicial.setPreferredSize(new java.awt.Dimension(1366, 768));

        areaMenu.setBackground(new java.awt.Color(255, 102, 0));

        logoBranca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoBranca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_white_small.png"))); // NOI18N

        botoesMenu.setBackground(new java.awt.Color(255, 102, 0));

        botaoVoos.setBackground(new java.awt.Color(255, 255, 255));
        botaoVoos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botaoVoos.setText("Vôos");
        botaoVoos.setBorder(null);
        botaoVoos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoVoosMouseClicked(evt);
            }
        });
        botaoVoos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botaoVoosKeyPressed(evt);
            }
        });

        botaoPassageiros.setBackground(new java.awt.Color(255, 255, 255));
        botaoPassageiros.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botaoPassageiros.setText("Passageiros");
        botaoPassageiros.setBorder(null);
        botaoPassageiros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoPassageirosMouseClicked(evt);
            }
        });
        botaoPassageiros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botaoPassageirosKeyPressed(evt);
            }
        });

        botaoReservas.setBackground(new java.awt.Color(255, 255, 255));
        botaoReservas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botaoReservas.setText("Reservas");
        botaoReservas.setBorder(null);
        botaoReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoReservasMouseClicked(evt);
            }
        });
        botaoReservas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botaoReservasKeyPressed(evt);
            }
        });

        botaoCancelamentos.setBackground(new java.awt.Color(255, 255, 255));
        botaoCancelamentos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botaoCancelamentos.setText("Cancelamentos");
        botaoCancelamentos.setBorder(null);
        botaoCancelamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCancelamentosMouseClicked(evt);
            }
        });
        botaoCancelamentos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botaoCancelamentosKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout botoesMenuLayout = new javax.swing.GroupLayout(botoesMenu);
        botoesMenu.setLayout(botoesMenuLayout);
        botoesMenuLayout.setHorizontalGroup(
            botoesMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botoesMenuLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(botaoVoos, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(botaoPassageiros, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(botaoReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(botaoCancelamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        botoesMenuLayout.setVerticalGroup(
            botoesMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botoesMenuLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(botoesMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoVoos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(botoesMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botaoReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botaoPassageiros, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botaoCancelamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout areaMenuLayout = new javax.swing.GroupLayout(areaMenu);
        areaMenu.setLayout(areaMenuLayout);
        areaMenuLayout.setHorizontalGroup(
            areaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaMenuLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(areaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(logoBranca)
                    .addComponent(botoesMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        areaMenuLayout.setVerticalGroup(
            areaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaMenuLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(logoBranca)
                .addGap(149, 149, 149)
                .addComponent(botoesMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout telaInicialLayout = new javax.swing.GroupLayout(telaInicial);
        telaInicial.setLayout(telaInicialLayout);
        telaInicialLayout.setHorizontalGroup(
            telaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        telaInicialLayout.setVerticalGroup(
            telaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVoosMouseClicked
        new Voos().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoVoosMouseClicked

    private void botaoPassageirosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoPassageirosMouseClicked
        new Passageiros().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoPassageirosMouseClicked

    private void botaoReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoReservasMouseClicked
        new Reservas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoReservasMouseClicked

    private void botaoCancelamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCancelamentosMouseClicked
        new Cancelamentos().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoCancelamentosMouseClicked

    private void botaoVoosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botaoVoosKeyPressed
        new Voos().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoVoosKeyPressed

    private void botaoPassageirosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botaoPassageirosKeyPressed
        new Passageiros().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoPassageirosKeyPressed

    private void botaoReservasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botaoReservasKeyPressed
        new Reservas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoReservasKeyPressed

    private void botaoCancelamentosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botaoCancelamentosKeyPressed
        new Cancelamentos().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoCancelamentosKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel areaMenu;
    private javax.swing.JButton botaoCancelamentos;
    private javax.swing.JButton botaoPassageiros;
    private javax.swing.JButton botaoReservas;
    private javax.swing.JButton botaoVoos;
    private javax.swing.JPanel botoesMenu;
    private javax.swing.JLabel logoBranca;
    private javax.swing.JPanel telaInicial;
    // End of variables declaration//GEN-END:variables
}
